# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    # Print the Linux version.
    uname -a
    # Print the gcc version.
    gcc --version
    #  Install a CMake 3.0.2 version.
    #- apt-get update -qq
    apt-get install cmake -y
    apt-get install cmake -y --force-yes
    # Print the CMake version.
    cmake --version          
    mkdir build
    cd build
    # Call the CMake.
    cmake ..
    # Build the project.
    make
  displayName: 'make'
  
  

