name: RocketSimulator CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure dependencies
      run: |
            ls
            chmod 775 configure.sh
            sudo ./configure.sh
    - name: Set Permissions
      run: |
            cd Software/
            chmod -R 777 .
    - name: build 2D Map
      run: |
            echo Build 2D Map 
