name: RocketSimulator CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure dependencies
      run: |
            ls
            chmod 775 configure.sh
            sudo ./configure.sh
    - name: Set Permissions
      run: |
            cd Software/
            chmod -R 777 .
    - name: Linter
      if: steps.filter.outputs.workflows == 'true'
      run: |
            cd Software
            cppcheck *.cc --force
    - name: build 2D Map
      run: |
            cd 2DMap
            mkdir build
            cd build
            cmake ..
            make