name: RocketSimulator CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ccahe dependencies
      run: |
            ls
            chmod 775 configure.sh
            sudo ./configure.sh
    - name: Linter
      if: steps.filter.outputs.workflows == 'true'
      run: |
            cppcheck *.cc --force
    - name: Build Controller and Libraries
      run: |
            mkdir build
            cd build
            cmake ..
            make
    - name: 2DMap Tests
      run: |
            cd 2DMap
            cd build
            ./exe2DMap-Test
    - name: Flight Algorithm Tests
      run: |
            cd Flight_Algorithm
            cd build
            ./exeFlight_Algorithm-Test
    - name: Land Algorithm Tests
      run: |
            cd Land_Algorithm
            cd build
            ./exeLand_Algorithm-Test
    - name: Controller Tests
      run: |
            cd build
            ./exeController-Test