name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
            ls
            ./configure
            cd Software/
            pwd
            chmod -R 777 .
            ./build_all.sh Azure
